#!/usr/bin/env bash
#$ -N deit_small
#$ -l mem=4G
#$ -cwd
#$ -pe default 2
#$ -o $HOME
#$ -e $HOME
#$ -l h=*beam*

export PATH="$HOME/miniconda/bin:$PATH"
eval "$(conda shell.bash hook)"
conda activate ChengThesis

# train DeiT-small on ImageNet on grid
python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py --model deit_small_patch16_224 --batch-size 256 --data-path /net/projects/data/ImageNet/ILSVRC2012 --output_dir $HOME

conda deactivate